coverage_service: cobertura_xml
xcodeproj: platforms/ios/example/Wysiwyg.xcodeproj
source_directory: platforms/ios/example/lib
output_directory: platforms/ios/example
build_directory: platforms/ios/example/DerivedData
ignore:
  - Sources/WysiwygComposer.swift