coverage_service: cobertura_xml
xcodeproj: platforms/ios/example/Wysiwyg.xcodeproj
source_directory: platforms/ios/example
output_directory: platforms/ios/example
build_directory: platforms/ios/example/DerivedData
ignore:
  - Wysiwyg/Mocks/*
  - Wysiwyg/AppDelegate.swift
  - lib/Sources/WysiwygComposer.swift