name: Rust

on:
  push:
    branches: [ "main" ]

env:
  CARGO_TERM_COLOR: always

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - name: Checkout
      uses: actions/checkout@v3
    - name: Build
      run: make web
    - name: Upload github-pages
      uses: actions/upload-pages-artifact
      with:
        dir: "platforms/web/example/"
    - name: Deploy github-pages
      uses: actions/deploy-pages
